name: Linters

on:
  pull_request: {}
  push: {}

jobs:
  gitlint:
    runs-on: ubuntu-latest
    name: GitLint
    steps:
      - name: Lint branches names
        uses: aschbacd/gitlint-action@v1.2.0
        with:
          re-branch-name: ^(feature|bugfix|hotfix|release|docs)\/.+$
          re-commit-message-subject: .*
